---
- hosts: "{{ cluster }}.frontends"
  remote_user: root
  vars_files:
    - ../conf/setup_vars.yml    
  tasks:
    - name: start all frontends
      shell:
        cmd: "sh {{ doris_home }}/fe/bin/start_fe.sh --daemon"
- hosts: "{{ cluster }}.backends"
  remote_user: root
  vars_files:
    - ../conf/setup_vars.yml    
  tasks:
    - name: start all backends
      shell:
        cmd: "sh {{ doris_home }}/be/bin/start_be.sh --daemon"
- hosts: "{{ cluster }}.brokers"
  remote_user: root
  vars_files:
    - ../conf/setup_vars.yml
  tasks:
    - name: start all brokers
      shell:
        cmd: "sh {{ doris_home }}/apache_hdfs_broker/bin/start_broker.sh --daemon"

