---
- hosts: "mysql_hosts"
  vars_files:
    - ../../vars.yml
  tasks:
    - name: upload mysql init-only-entry
      copy:
        src: "init-only-entry.sh"
        dest: "{{ mysql_path }}"
    - name: init mysql
      docker_container:
        name: mysql-initializer
        image: mysql:8.0.39-debian
        command: init-only-entry.sh mysqld
        env:
          MYSQL_ROOT_PASSWORD: 'P@ssw0rd'
        volumes:
          - "{{ mysql_path }}/init-only-entry.sh:/usr/local/bin/init-only-entry.sh"
          - "{{ mysql_data_path }}:/var/lib/mysql"