---
- hosts: "{{ cluster }}.master"
  remote_user: root
  vars_files:
    - ../conf/setup_vars.yml
    - ../conf/{{ cluster }}.yml
  tasks:
    - name: add folower
      shell:
        cmd: echo "alter system add follower \"{{ item }}:{{ edit_log_port }}\";" | mysql -h127.0.0.1 -P{{ query_port }} -uroot
      with_items: "{{follower}}"
    - name: add backends
      shell:
        cmd: echo "alter system add BACKEND \"{{ item }}:{{ heartbeat_service_port }}\";" | mysql -h127.0.0.1 -P{{ query_port }} -uroot
      with_items: "{{backends}}"
    - name: add brokres
      shell:
        cmd: echo "alter system add broker broker1  \"{{ item }}:{{ broker_ipc_port }}\";" | mysql -h127.0.0.1 -P{{ query_port }} -uroot
      with_items: "{{brokers}}"
